pySource/app/__init__.py
import os
from os import path
from flask import Flask

from flask_moment import Moment
from config import config
from flask_uploads import patch_request_class


moment = Moment()

basedir = path.abspath(path.dirname(__file__))

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    
    basedir = path.abspath(path.dirname(__file__))

    MUSIC_FOLDER = os.path.join(basedir, 'static/musics')
    app.config['MUSIC_FOLDER'] = MUSIC_FOLDER

    moment.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from . import db
    db.init_app(app)
    if not os.path.exists("flaskr.sqlite"):
        with app.app_context():
            db.init_db()

    return app

pySource/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors, extras

pySource/app/main/views.py
import os
from flask import render_template, request, flash, redirect, url_for, jsonify, make_response
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename
from . import main
from manage import app


home_visit = False

@main.route('/healthcheck')
def healthcheck():
    return "200"


@main.route('/')
@main.route('/home', methods=['GET', 'POST'])
def home():
    global home_visit
    home_visit = True
    return render_template('music/home.html')

@main.route('/play', methods=['GET', 'POST'])
def player():
    if home_visit:
        music_folder = app.config['MUSIC_FOLDER']
        music_list = os.listdir(music_folder)
        return render_template('music/play.html', music_list = music_list)
    else:
        home()

pySource/app/templates/music/home.html
<html>

<body>	
<center>
	<div>
    <img src="{{ url_for( 'main.download_file', filename = 'BizTec.png' ) }}" alt="logo" style="width:290px;height:150px;">
		<h1> BizTec Music Player </h1>
		<br>
	</div>

	<button type="button" onclick="window.location.href='{{ url_for( 'main.player' ) }}';">Player</button>

</center>
</body>

</html>

pySource/app/templates/music/index.html
<html>

<head>
	<link rel="stylesheet" type="text/css" href="../static/css/music_index.css">
</head>


<body>	

	<div>
		<h1> Music Visual </h1>
		<br>
	    <ul class="type" id="type">
	    	<li>Column</li>
	    </ul>

	    <br>
	    <div >
	    	Volume <br>
	    	<input id="volume" type="range" min="0" max="100" value="60">
	    </div>
	</div>


	<div class="left">
		<ul id="list">
			{% for music in music_list %}
			<li title="{{music}}">{{music}}</li>
			{% endfor %}
		</ul>

	</div>


	<!--<div class="right" id="box"></div>-->


	<script type="text/javascript" src="../static/js/music_index.js"> </script>


</body>

</html>

pySource/app/templates/music/play.html
<html>

<head>
	<link rel="stylesheet" type="text/css" href="../static/css/music_index.css">
</head>


<body>	

	<div>
		<h1> Music Visual </h1>

	    <br>
	    <div >
	    	Volume <br>
	    	<input id="volume" type="range" min="0" max="100" value="60" list="volsettings">
			<datalist id="volsettings">
				<option>0</option>
				<option>20</option>
				<option>40</option>
				<option>60</option>
				<option>80</option>
				<option>100</option>
			</datalist>
			<output for="volume" id="outvolume">60</output>%
	    </div>
	</div>

	<center>
		<div class="musiclist">
			<ul id="list">
				{% for music in music_list %}
				<li title="{{music}}">{{music}}</li>
				{% endfor %}
			</ul>
		</div>
	</center>

	<script type="text/javascript" src="../static/js/music_index.js"> </script>


</body>

</html>

pySource/app/templates/music/play2.html
<html>

<head>
	<link rel="stylesheet" type="text/css" href="../static/css/music_index.css">
</head>


<body>	

	<div>
		<h1> Music Visual </h1>

	    <br>
	    <div >
	    	Volume <br>
	    	<input id="volume" type="range" min="0" max="100" value="60" list="volsettings">
			<datalist id="volsettings">
				<option>0</option>
				<option>20</option>
				<option>40</option>
				<option>60</option>
				<option>80</option>
				<option>100</option>
			</datalist>
			<output for="volume" id="outvolume">60</output>%
	    </div>
	</div>

	<center>
		<div class="musiclist">
			<ul id="list">
				{% for music in music_list %}
				<li title="{{music}}">{{music}}</li>
				{% endfor %}
			</ul>
		</div>
	</center>

	<script type="text/javascript" src="../static/js/music_index.js"> </script>


</body>

</html>